apiVersion: v1
kind: Service
metadata:
  name: argocd-server
  namespace: argocd
spec:
  selector:
    app.kubernetes.io/name: argocd-server
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8080
      nodePort: 30080
  type: NodePort

# kubectl get svc argocd-server -n argocd -o yaml > argocd-nodeport-svc.yaml
# kubectl apply -f kind/kubernetes/argocd/argocd-nodeport-svc.yaml