apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-prometheus-nginx-exporter
  namespace: monitoring
  labels:
    app: nginx-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-exporter
  template:
    metadata:
      labels:
        app: nginx-exporter
    spec:
      containers:
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:0.11.0
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9113
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 256Mi
              cpu: 200m
      #     volumeMounts:
      #       - name: nginx-exporter-config
      #         mountPath: /etc/nginx/nginx.conf
      #         subPath: nginx.conf
      #         readOnly: true
      # volumes:
      # - name: nginx-exporter-config
      #   configMap:
      #     name: nginx-exporter-config
      #     items:
      #       - key: nginx.conf
      #         path: nginx.conf