apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: nginx-exporter-svc
  labels:
    app: nginx-exporter
spec:
  selector:
    app: nginx-exporter
  ports:
    - name: http
      port: 9113
      targetPort: 9090
      nodePort: 30113
  type: NodePort