apiVersion: apps/v1
kind: Deployment
metadata:
  name: blackbox-exporter # prometheus-prometheus-nginx-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: blackbox-exporter
          image: quay.io/prometheus/blackbox-exporter:v0.23.0 # nginx/nginx-prometheus-exporter:0.11.0 #
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 9115
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: http
          resources:
            requests:
              memory: 256Mi
              cpu: 300m
            limits:
              memory: 512Mi
              cpu: 400m