apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: {{ .Values.nginx.namespace }}
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Kubernetes nodeport working!</title>
        <!-- <link rel="stylesheet" href="../styles.css"> -->
    </head>
    <body>
        <div class="content">
            <h1>Kubernetes nodeport working!</h1>
            <p>Nginx server running...</p>
        </div>
    </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: {{ .Values.nginx.namespace }}
data:
  nginx.conf: |
    user nginx;
    worker_processes 1;
    events {
      worker_connections 10240;
    }

    http {
      
      server {
        listen 80;
        server_name _nginx;
        location /status {
          stub_status;
        }
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
      }

      server {
        listen 8081;
        server_name metrics_exporter;
        location /metrics {
          # access_log off;
          stub_status;
        }
      }
    }