apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nginx.deployment.name }}
  namespace: {{ .Values.nginx.namespace }}
spec:
  replicas: {{ .Values.nginx.deployment.replicas }}
  selector:
    matchLabels:
      app: nginx-canary
  template:
    metadata:
      labels:
        app: nginx-canary
    spec:
      containers:
      - name: nginx-canary
        image: {{ .Values.nginx.deployment.image }}
        ports:
        - name: http
          containerPort: {{ .Values.nginx.service.port }}
          protocol: TCP
        livenessProbe:
          httpGet:
            path: {{ .Values.nginx.deployment.probePath }}
            port: {{ .Values.nginx.service.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: {{ .Values.nginx.deployment.probePath }}
            port: {{ .Values.nginx.service.port }}
          initialDelaySeconds: 30
          periodSeconds: 10