apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.nginx.ingress.name }}
  namespace: {{ .Values.nginx.namespace }}
spec:
  ingressClassName: {{ .Values.nginx.ingress.ingressClassName }}
  rules:
  - host: {{ .Values.nginx.ingress.host }} # Specify the hostname for which the Ingress applies
    http:
      paths:
      - path: /
        pathType: Prefix  # Type of path matching
        backend:
          service:
            name: {{ .Values.nginx.service1.name }}
            port:
              number: {{ .Values.nginx.service1.port }}