apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.nginx.roles.admin }}
  namespace: {{ .Values.nginx.namespace }}
rules:
- apiGroups: ["*"]
  resources: ["statefulsets", "pods", "pods/exec", "services", "configmaps", "secrets"]
  verbs: ["create", "get", "list", "watch", "delete", "patch", "describe"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.nginx.roles.read }}
  namespace: {{ .Values.nginx.namespace }}
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets", "pods", "services", "configmaps"]
  verbs: ["get", "list", "watch"]