apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.nginx.roles.admin }}
  namespace: {{ .Values.nginx.namespace }}
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.nginx.roles.read }}
  namespace: {{ .Values.nginx.namespace }}
rules:
- apiGroups: [""]
  resources: ["pods", "deployments", "services", "replicasets", "statefulsets"]
  verbs: ["get", "watch", "list"]