apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nginx.serviceaccount.adminSecret }}
  namespace: {{ .Values.nginx.namespace }}
type: Opaque
data:
  token: YWRtaW4tc2EtcGFzc3dvcmQ=
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nginx.serviceaccount.readSecret }}
  namespace: {{ .Values.nginx.namespace }}
type: Opaque
data:
  token: cmVhZG9ubHktc2EtcGFzc3dvcmQ=