apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.nginx.statefulset.name }}
  namespace: {{ .Values.nginx.namespace }}
  labels:
    prometheus: prometheus-kube-prometheus-prometheus
spec:
  selector:
    matchLabels:
      app: nginx-monitoring
  namespaceSelector:
    matchNames:
      - {{ .Values.nginx.namespace }}
  endpoints:
    - port: http-metrics
      path: /metrics