apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.nginx.serviceaccount.adminRole }}
  namespace: {{ .Values.nginx.namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.nginx.serviceaccount.readRole }}
  namespace: {{ .Values.nginx.namespace }}