apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.service.name }}
  namespace: {{ .Values.nginx.namespace }}
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: http
      port: {{ .Values.nginx.service.port }}
      targetPort: {{ .Values.nginx.service.port }}
      nodePort: {{ .Values.nginx.service.nodeport }}
    - name: http-metrics
      port: {{ .Values.nginx.service.portMetrics}}
      targetPort: {{ .Values.nginx.service.portMetrics}}