apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.service1.name }}
  namespace: {{ .Values.nginx.namespace }}
spec:
  type: {{ .Values.nginx.service1.type}}
  selector:
    app: nginx
  ports:
    - name: http
      port: {{ .Values.nginx.service1.port }}
      targetPort: http
      # nodePort: {{ .Values.nginx.service1.nodeport }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.service2.name }}
  namespace: {{ .Values.nginx.namespace }}
  labels:
    app: nginx-monitoring
spec:
  type: {{ .Values.nginx.service2.type}}
  selector:
    app: nginx
  ports:
    - name: http-metrics
      port: {{ .Values.nginx.service2.port}}
      targetPort: http-metrics