apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.nginx.serviceaccount.adminRole }}
  namespace: {{ .Values.nginx.namespace }}
secrets: 
- name: {{ .Values.nginx.serviceaccount.adminSecret }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.nginx.serviceaccount.readRole }}
  namespace: {{ .Values.nginx.namespace }}
secrets: 
- name: {{ .Values.nginx.serviceaccount.readSecret }}