apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/marcusmvbs/argocd-features.git
    targetRevision: HEAD
    path: charts/dev/nginx
  destination:
    server: https://172.24.0.4:6443
    namespace: webserver
  syncPolicy:
    automated:
      selfHeal: true
      prune: true