apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
  namespace: argocd-ns
spec:
  project: argocd-features
  source:
    repoURL: https://github.com/marcusmvbs/argocd-features.git
    targetRevision: main
    path: charts/dev/nginx
  destination:
    server: https://kubernetes.default.svc
    namespace: webserver-ns
  syncPolicy:
    automated:
      selfHeal: true
      prune: true