apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: webserver-ns
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: bitnami/nginx
        resources: 
          limits:
            cpu: 1
            memory: 128Mi
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
      dnsPolicy: ClusterFirst
      restartPolicy: Always