apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: nginx-exporter-svc
  labels:
    app: nginx-exporter
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9113
      targetPort: http
  selector:
    app: nginx-exporter