apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress-nginx-ingress-controller
  namespace: nginx-ingress
spec:
  loadBalancerIP: 34.41.215.157 # Current task GCP external IP
  ports:
  - name: http
    # nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: http
  type: LoadBalancer