apiVersion: apps/v1
kind: Deployment
metadata:
  name: goapp
  namespace: webserver
  labels:
    monitoring: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goapp
  template:
    metadata:
      labels:
        app: goapp
    spec:
      containers:
        - name: goapp
          image: golang:1.22.1-alpine3.19
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 81
            - name: http-metrics
              containerPort: 8181
          resources:
            requests:
              memory: 256Mi
              cpu: 200m
            limits:
              memory: 512Mi
              cpu: 400m
          volumeMounts:
            - name: config-volume
              mountPath: /app_config
            - name: script-volume
              mountPath: /app_config/script
          # command: ["sh", "-c", "cp /app_config/script/app_config.sh /tmp/app_config.sh && cp -r /app_config/ /tmp/ && /tmp/app_config.sh"] # debug ["sh", "-c", "tail -f /dev/null"]
          command:
            - "/bin/sh"
            - "-c"
            - |
              cp /app_config/script/app_config.sh /tmp/app_config.sh &&
              cp -r /app_config/ /tmp/app_config &&
              chmod +x /tmp/app_config.sh &&
              sh /tmp/app_config.sh
          
      # Define ConfigMaps for configuration files
      volumes:
        - name: config-volume
          configMap:
            name: go-app
        - name: script-volume
          configMap:
            name: go-script