apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000 # Nginx nodePort
    hostPort: 30000
    protocol: TCP
  - containerPort: 30003 # Grafana nodePort
    hostPort: 30003
    protocol: TCP
  - containerPort: 30005 # Prometheus Nginx Exporter nodePort
    hostPort: 30005
    protocol: TCP
  - containerPort: 30080 # Argocd nodePort
    hostPort: 30080
    protocol: TCP
  - containerPort: 30081 # Golang app
    hostPort: 30081
    protocol: TCP
  - containerPort: 30500 # Kubernetes-Dashboard nodePort ## No need for kubectl port-forward ##
    hostPort: 30500
    protocol: TCP
  - containerPort: 32000 # Prometheus nodePort
    hostPort: 32000
    protocol: TCP
  - containerPort: 30115 # Prometheus Nginx Exporter nodePort
    hostPort: 30115
    protocol: TCP
- role: worker