apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 8443 # No need for kubectl port-forward
    hostPort: 8443
    protocol: TCP
  - containerPort: 3000
    hostPort: 3000
    protocol: TCP
  - containerPort: 8080
    hostPort: 8080
    protocol: TCP
  - containerPort: 9001
    hostPort: 9001
    protocol: TCP
  - containerPort: 9090 
    hostPort: 9090
    protocol: TCP
  - containerPort: 30000 # Nginx nodePort
    hostPort: 30000
    protocol: TCP
  - containerPort: 31000 
    hostPort: 31000
    protocol: TCP
  - containerPort: 32000 # Kubernetes-Dashboard nodePort
    hostPort: 32000
    protocol: TCP
- role: worker