apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.aspnet.deployment.name }}
  namespace: {{ .Values.aspnet.namespace }}
spec:
  replicas: {{ .Values.aspnet.deployment.replicas }}
  selector:
    matchLabels:
      app: aspnet
  template:
    metadata:
      labels:
        app: aspnet
    spec:
      containers:
      - name: aspnet
        image: {{ .Values.aspnet.deployment.image }}
        ports:
        - containerPort: {{ .Values.aspnet.service.port }}