apiVersion: v1
kind: Service
metadata:
  name: goapp-np-svc
  namespace: webserver
spec:
  type: NodePort
  selector:
    app: goapp
  ports:
    - name: http
      port: 81
      targetPort: 81
      nodePort: 30081
---
apiVersion: v1
kind: Service
metadata:
  name: goapp-metrics-svc
  namespace: webserver
  labels:
    app: nginx-monitoring
spec:
  type: ClusterIP
  selector:
    app: goapp
  ports:
    - name: http-metrics
      port: 8181
      targetPort: http-metrics