apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: blackbox-exporter-svc
spec:
  selector:
    app: nginx
  ports:
    - name: http
      port: 9115
      targetPort: 9115
      # nodePort: 30115
  type: ClusterIP