apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.prometheus.grafana-service.namespace }}
  namespace: {{ .Values.prometheus.namespace }}
spec:
  selector:
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: grafana
  ports:
    - protocol: TCP
      port: {{ .Values.prometheus.grafana-service.port }}
      targetPort: {{ .Values.prometheus.grafana-service.targetPort }}
      nodePort: {{ .Values.prometheus.grafana-service.nodeport }}
  type: NodePort