apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: {{ .Values.prometheus.prom-server.name }}
  namespace: {{ .Values.prometheus.namespace }}
spec:
  version: {{ .Values.prometheus.prom-server.version }}
  serviceAccountName: prometheus-sa
  podMonitorSelector:
    matchLabels:
      prometheus: {{ .Values.prometheus.prom-server.name }}
  podMonitorNamespaceSelector:
    matchLabels:
      monitoring: prometheus
  serviceMonitorSelector:
    matchLabels:
      prometheus: {{ .Values.prometheus.prom-server.name }}
  serviceMonitorNamespaceSelector:
    matchLabels:
      monitoring: prometheus
  # probeSelector:
  #   matchLabels:
  #     prometheus: {{ .Values.prometheus.prom-server.name }}
  # probeNamespaceSelector:
  #   matchLabels:
  #     monitoring: prometheus
  additionalScrapeConfigs:
    name: prometheus-config
    key: prometheus-additional.yml
  resources:
    requests:
      cpu: 500m
      memory: 2Gi
    limits:
      cpu: 500m
      memory: 2Gi
  replicas: {{ .Values.prometheus.prom-server.replicas }}
  logLevel: info
  logFormat: logfmt
  retention: 7d
  scrapeInterval: 30s
  securityContext:
    fsGroup: 0
    runAsNonRoot: false
    runAsUser: 0
  storage:
    volumeClaimTemplate:
      spec:
        resources:
          requests:
            storage: 20Gi