apiVersion: v1
kind: Secret
metadata:
  name: prometheus-config
  namespace: {{ .Values.prometheus.namespace }}
  labels:
    prometheus: {{ .Values.prometheus.prom-server.name }}
stringData:
  prometheus-additional.yml: |-
    - job_name: "blackbox-exporter"
      scrape_interval: 16s
      static_configs:
        - targets: ["blackbox-exporter-svc.monitoring:9115"]
    - job_name: "node-exporter"
      scrape_interval: 16s
      static_configs:
        - targets: ["localhost:9100"]
    - job_name: "nginx-metrics"
      scrape_interval: 16s
      static_configs:
        - targets: ["nginx-metrics-svc.webserver:8081"]
# - job_name: "node-exporter"
# # metrics_path defaults to '/metrics'
# # scheme defaults to 'http'.
# scrape_interval: 16s
# evaluation_interval: 16s
# # scrape_timeout is set to the global default (10s).
# static_configs:
#   - targets: ["localhost:8080", "localhost:9090", "localhost:9093", "localhost:9100"]