apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
  namespace: webserver
data:
  index.html: |
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Kubernetes nodeport working!</title>
        <!-- <link rel="stylesheet" href="../styles.css"> -->
    </head>
    <body>
        <div class="content">
            <h1>Kubernetes nodeport working!</h1>
            <p>Nginx server running...</p>
        </div>
    </body>
    </html>
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: webserver
data:
  nginx.conf: |
    # user nginx;
    # worker_processes 1;
    events {
      worker_connections 1024;
    }

    http {

      # upstream web-blue {
      #   server web-blue-01:80;
      #   server web-blue-02:80;
      # }

      # upstream web-green {
      #   server web-green-01:80;
      #   server web-green-02:80;
      # }

      server {
        listen 80;
        server_name _;

        location /status {
          stub_status;
        }
        location / {
          root /usr/share/nginx/html;
          index index.html;
        }
      }

      server {

        listen 9113;
        server_name exporter;

        location /nginx_status {
          stub_status;
        }
      }
    }