apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: sa-token-secret
  namespace: webserver
  annotations:
    kubernetes.io/service-account.name: "webserver-admin-sa"