apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: webserver
spec:
  type: NodePort
  selector:
    app: nginx # switch to nginx-canary if needed for rollout
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 32000