apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
  namespace: webserver
spec:
  serviceName: nginx
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      serviceAccountName: webserver-admin-sa
      containers:
        - name: nginx
          image: nginx:1.25.4
          ports:
            - protocol: TCP
              name: http
              containerPort: 80
          volumeMounts:
            - name: html-index
              mountPath: /usr/share/nginx/html/
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
          livenessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /index.html
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
      - name: html-index
        configMap:
          name: nginx-index
      - name: nginx-conf
        configMap:
          name: nginx-config
          items:
            - key: nginx.conf
              path: nginx.conf