apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-vol
  namespace: webserver
spec:
  serviceName: nginx
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:1.25.4
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-index
              mountPath: /usr/share/nginx/html/
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
      volumes:
      - name: html-index
        configMap:
          name: nginx-index
      - name: nginx-conf
        configMap:
          name: nginx-config
          items:
            - key: nginx.conf
              path: nginx.conf

# Apply -> configmap.yaml -> statefulset.yaml -> service.yaml

## Commands ##
# kubectl apply -f kind/kubernetes/nginx/configmap.yaml
# kubectl apply -f kind/kubernetes/nginx/statefulset.yaml
# kubectl apply -f kind/kubernetes/nginx/service.yaml
# http://localhost:30000/status

# kubectl exec web-vol-0 -n webserver -it -- sh / ls /usr/share/nginx/html/
# nginx -t / nginx -V / systemctl reload nginx

## Debug ##
# watch kubectl get pods -n webserver
# kubectl describe pod web-vol-0 -n webserver
# kubectl logs web-vol-0 -n webserver
# kubectl get cm nginx-html -n webserver -o yaml > cm-html.yaml
# kubectl describe cm nginx-html -n webserver

# kubectl delete statefulsets web-vol -n webserver
# kubectl delete cm nginx-index -n webserver

# useradd --system --no-create-home --shell /bin/false nginx-exporter
# curl localhost:9113/metrics - nginx exporter