apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.controller.service.name }}
  namespace: {{ .Values.controller.namespace }}
spec:
  selector:
    app: nginx-ingress
  ports:
    - protocol: TCP
      port: {{ .Values.controller.service.port1 }}
      targetPort: {{ .Values.controller.service.port1 }}
    - protocol: TCP
      port: {{ .Values.controller.service.port2 }}
      targetPort: {{ .Values.controller.service.port2 }}