apiVersion: v1
kind: Secret
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    prometheus: prometheus-kube-prometheus-prometheus
stringData:
  prometheus-additional.yml: |-
    - job_name: probe/monitoring/nginx-scrape
      scrape_interval: 16s
      static_configs:
        - targets: ["blackbox-exporter-svc.monitoring:9115"]
    - job_name: serviceMonitor/monitoring/prometheus-prometheus-node-exporter/0
      scrape_interval: 16s
      static_configs:
        - targets: ["prometheus-prometheus-node-exporter.monitoring:9100"]
    - job_name: podMonitor/webserver/goapp/0
      scrape_interval: 16s
      static_configs:
        - targets: ["goapp-metrics-svc.webserver:8181"]