apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: {{ .Values.deployment.namespace }}
  labels:
    app: nginx
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: {{ .Values.deployment.image }}
        resources: 
          limits:
            cpu: {{ .Values.deployment.cpu }}
            memory: {{ .Values.deployment.memory }}
        ports:
        - containerPort: {{ .Values.deployment.ports.port1 }}
        - containerPort: {{ .Values.deployment.ports.port2 }}
      dnsPolicy: {{ .Values.deployment.dnsPolicy }}
      restartPolicy: {{ .Values.deployment.restartPolicy }}