nginx:
  enabled: true
  namespace: webserver-ns

  service:
    name: nginx-svc
    namespace: webserver-ns
    port: 80
    annotations: {}

  deployment:
    name: nginx-argo
    namespace: webserver-ns
    replicas: 2
    image: nginx:1.25

  # ingress:
  #   enabled: true
  #   namespace: webserver-ns