nginx:
  deployment:
    namespace: webserver-ns
    name: nginx-deploy
    replicas: 3
    image: nginx:1.25
    # cpu: 1
    # memory: 128Mi
    ports:
      - containerPort1: 80
      - containerPort2: 443
    dnsPolicy: ClusterFirst
    restartPolicy: Always

    # ingress:
  #   enabled: true
  #   namespace: webserver-ns
  
  # service:
  #   annotations: {}
  #   name: nginx-svc
  #   ports:
  #     - containerPort1: 80
  #     - containerPort2: 443