apiVersion: v1
kind: Service
metadata:
  name: pythonapp-svc
  namespace: webserver
spec:
  type: NodePort
  selector:
    app: pythonapp
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30005
---
apiVersion: v1
kind: Service
metadata:
  name: pythonapp-svc
  namespace: webserver
  labels:
    app: nginx-monitoring
    # app.kubernetes.io/name: {{ include "python-app.name" . }}
    # helm.sh/chart: {{ include "python-app.chart" . }}
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 5001
      targetPort: http-metrics
  selector:
    app: pythonapp
    # app.kubernetes.io/name: {{ include "python-app.name" . }}
    # app.kubernetes.io/instance: {{ .Release.Name }}