apiVersion: apps/v1
kind: Deployment
metadata:
  name: pyflask-app
  namespace: webserver
  labels:
    monitoring: prometheus
    # app.kubernetes.io/name: {{ include "python-app.name" . }}
    # helm.sh/chart: {{ include "python-app.chart" . }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pyflask-app
    #   app.kubernetes.io/name: {{ include "python-app.name" . }}
    #   app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: pyflask-app
    #     app.kubernetes.io/name: {{ include "python-app.name" . }}
    #     app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: pyflask-app
          image: 21121953/pyflask_app
          ports:
            - name: http
              containerPort: 5000
            - name: http-metrics
              containerPort: 5001