apiVersion: v1
kind: Service
metadata:
  name: pyflask-np-svc
  namespace: webserver
spec:
  selector:
    app: pyflask-app
  ports:
    - name: http
      port: 5000
      targetPort: 5000
      nodePort: 30005
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: pyflask-metrics-svc
  namespace: webserver
  labels:
    app: nginx-monitoring
spec:
  selector:
    app: pyflask-app
  ports:
    - name: http-metrics
      port: 5001
      targetPort: http-metrics
  type: ClusterIP
