apiVersion: v1
kind: Secret
metadata:
  namespace: monitoring
  name: scrape-config
stringData:
  prometheus-additional.yaml: |-
    - job_name: node-exporter
      static_configs:
      - targets: ['localhost:9100']
      relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: nginx-exporter:9100