apiVersion: v1
kind: Service
metadata:
  name: prometheus-operated
  namespace: monitoring
spec:
  selector:
    app.kubernetes.io/name: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 32000
  type: NodePort

  # http://localhost:32000/config

  # Grafana - Data source Prometheus -> http://prometheus-operated.monitoring:9090
  # Create dashboard