prometheus:
  enabled: true
  namespace: monitoring

  grafanaservice:
    name: prometheus-grafana
    port: 80
    targetPort: 3000
    nodeport: 30003
  
  prometheusservice:
    name: prometheus-operated
    port: 9090
    nodeport: 32000
  
  promserver:
    name: prometheus-kube-prometheus-prometheus
    replicas: 1
    image: 