apiVersion: kyverno.io/v1
kind: ClusterPolicy 
# kind: Policy (Would be applied only in this namespace)
metadata:
  name: {{ .Values.kyverno.clusterpolicy.name }}
spec:
  validationFailureAction: {{ .Values.kyverno.clusterpolicy.validationFailureAction }}
  rules:
  - name: validate-limits
    match:
      resources:
        kinds:
        - {{ .Values.kyverno.clusterpolicy.kinds }}
    validate:
      message: {{ .Values.kyverno.clusterpolicy.message }}
      pattern:
        spec:
          containers:
          - name: "*"
            resources:
              limits:
              # The limits must be defined for all pods
                memory: {{ .Values.kyverno.clusterpolicy.memory }}
                cpu: {{ .Values.kyverno.clusterpolicy.cpu }}