apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.service.name }}
  namespace: {{ .Values.nginx.namespace }}
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: {{ .Values.nginx.service.port1 }}
      targetPort: {{ .Values.nginx.service.port1 }}
    - protocol: TCP
      port: {{ .Values.nginx.service.port2 }}
      targetPort: {{ .Values.nginx.service.port2 }}