apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kind-admin
rules:
- apiGroups: [""] # indicates the core API group
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kind-readonly
rules:
- apiGroups: [""] 
  resources: ["pods", "deployments", "services", "replicasets", "statefulsets"]
  verbs: ["get", "watch", "list"]