apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: app-admin
rules:
- apiGroups: [""] # indicates the core API group
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: app-readonly
rules:
- apiGroups: [""] 
  resources: ["pods", "deployments", "services", "replicasets", "statefulsets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus
rules:
  - apiGroups: [""] 
    resources:
      - nodes
      - nodes/metrics
      - services
      - endpoints
      - pods
    verbs: ["get", "watch", "list"]
  - apiGroups: [""] 
    resources:
      - configmaps
    verbs: ["get"]
  # - apiGroups: 
  #     - networking.k8s.io
  #   resources:
  #     - ingress
  #   verbs: ["get", "watch", "list"]
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]