apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: nginx-probe
  namespace: monitoring
  labels:
    prometheus: prometheus-prometheus-kube-prometheus-prometheus
spec:
  jobName: web_scrape
  interval: 30s
  module: http_2xx
  prober:
    path: /index.html
    url: blackbox-exporter-svc.monitoring:9115
  targets:
    staticConfig:
      static:
        - http://nginx-np-svc.webserver:80/index.html