apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin-role
  namespace: webserver
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: read-role
  namespace: webserver
rules:
- apiGroups: [""] # indicates the core API group
  resources: ["pods", "deployments", "services", "replicasets", "statefulsets"]
  verbs: ["get", "watch", "list"]