apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-sa
  namespace: kubernetes-dashboard
---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: general-admin-sa
#   namespace: default