apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-sa
  namespace: kubernetes-dashboard
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: webserver-admin-sa
  namespace: webserver
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: webserver-readonly-sa
#   namespace: webserver
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: general-admin-sa
#   namespace: default
