apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.nginx.statefulset.name }}
  namespace: {{ .Values.nginx.namespace }}
spec:
  replicas: {{ .Values.nginx.deployment.replicas }}
  selector:
    matchLabels:
      app: nginx-canary
  serviceName: {{ .Values.nginx.service.name }}
  template:
    metadata:
      labels:
        app: nginx-canary
    spec:
      containers:
        - name: nginx-canary
          image: {{ .Values.nginx.deployment.image }}
          ports:
            - containerPort: {{ .Values.nginx.service.port }}
          volumeMounts:
            - name: nginx-volume
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.nginx.statefulset.storage }}
